---
abstract: "Manipulate 'remind' output with Perl"
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: GPL
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Remind-Event
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  DateTime: 0
  DateTime::Duration: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Date-Remind-Event
  repository: git://github.com/mlawren/date-remind-event.git
version: 0.04
